# -*- coding: utf-8 -*-
"""psm dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ujfvMvk-I47A69--Ksyqwdi_EbeX0Sb

#dataset loading and analysis
"""

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

data = fetch_ucirepo(id=165)

X = data.data.features
y = data.data.targets

import pandas as pd

df = pd.concat([X, y], axis=1)

df.head()

df.info()

df.isna().sum()

df.describe()

df.columns

df.shape

df.sample(5)

df.describe().T[["min", "max"]]

"""# rawdataset visualization"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

columns = [
    "Cement",
    "Blast Furnace Slag",
    "Fly Ash",
    "Water",
    "Superplasticizer",
    "Coarse Aggregate",
    "Fine Aggregate",
    "Age",
    "Concrete compressive strength"
]

x_labels = {
    "Cement": "Cement content (kg/m³)",
    "Blast Furnace Slag": "Blast furnace slag content (kg/m³)",
    "Fly Ash": "Fly ash content (kg/m³)",
    "Water": "Water content (kg/m³)",
    "Superplasticizer": "Superplasticizer content (kg/m³)",
    "Coarse Aggregate": "Coarse aggregate content (kg/m³)",
    "Fine Aggregate": "Fine aggregate content (kg/m³)",
    "Age": "Age (days)",
    "Concrete compressive strength": "Concrete compressive strength (MPa)"
}

def fd_bins(x):
    x = np.asarray(x.dropna())
    n = len(x)
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1

    if iqr == 0:
        return 10

    bin_width = 2 * iqr / (n ** (1 / 3))

    if bin_width == 0:
        return 10

    bins = int(np.ceil((x.max() - x.min()) / bin_width))
    return max(bins, 1)

fig, axes = plt.subplots(3, 3, figsize=(14, 10))
axes = axes.flatten()

for ax, col in zip(axes, columns):
    if col == "Age":
        counts = df[col].value_counts().sort_index()
        ax.bar(counts.index.astype(str), counts.values)
        ax.set_xlabel(x_labels[col])
        ax.tick_params(axis="x", rotation=45)
    else:
        bins = fd_bins(df[col])
        ax.hist(df[col], bins=bins, edgecolor="black")
        ax.set_xlabel(x_labels[col])

    ax.set_ylabel("Number of samples")
    ax.set_title(col, fontsize=11)
    ax.grid(axis="y", alpha=0.3)

fig.suptitle(
    "Empirical Distributions of Variables in the Concrete Compressive Strength Dataset",
    fontsize=15,
    y=1.02
)

plt.tight_layout()
plt.savefig("raw_dataset_histogram_grid_fd_rule.png", dpi=300, bbox_inches="tight")
plt.show()

"""# outlier check"""

plt.figure(figsize=(20,10))

df.boxplot()

plt.xlabel("Variables")
plt.ylabel("Original Measurement Units")
plt.title("Boxplots of Numerical Variables")

plt.grid(alpha=0.3)

plt.show()

"""- The green line inside the box represents the median (Q2), corresponding to the 50th percentile.

- The lower edge of the box represents the first quartile (Q1), corresponding to the 25th percentile.

- The upper edge of the box represents the third quartile (Q3), corresponding to the 75th percentile.

- The upper whisker represents the largest non-outlier value, defined as:
  
  \[
  Q_3 + 1.5 \times IQR
  \]

- The lower whisker represents the smallest non-outlier value, defined as:
  
  \[
  Q_1 - 1.5 \times IQR
  \]

- The box contains the middle 50% of the data and its width corresponds to the interquartile range (IQR):
  
  \[
  IQR = Q_3 - Q_1
  \]

- The circles beyond the whiskers represent outliers.
"""

def get_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return series[(series < lower) | (series > upper)]

cols = [
    "Blast Furnace Slag",
    "Water",
    "Superplasticizer",
    "Fine Aggregate",
    "Age",
    "Concrete compressive strength"
]

for col in cols:
    outliers = get_outliers(df[col])

    print("\n" + "="*50)
    print(col)
    print("Number of outliers:", len(outliers))
    print("Unique values:")
    print(sorted(outliers.unique()))

age_outliers = get_outliers(df["Age"])

age_outliers.value_counts().sort_index()

"""# (floc=0) strength distribution analysis & fitting -"""

values = df["Concrete compressive strength"]

values.min(), values.max()

import numpy as np

values = df["Concrete compressive strength"]

q75, q25 = np.percentile(values, [75, 25])
iqr = q75 - q25
h = 2 * iqr / (len(values) ** (1/3))
print(h)

bins = np.arange(values.min(), values.max() + h, h)
len(bins)

import numpy as np
import matplotlib.pyplot as plt

counts, edges = np.histogram(values, bins=bins)

pmf = counts / counts.sum()

centers = (edges[:-1] + edges[1:]) / 2
widths = np.diff(edges)

plt.figure(figsize=(7, 5))
plt.bar(centers, pmf, width=widths, align="center", edgecolor="black")

plt.title("Empirical PMF of Concrete Compressive Strength")
plt.xlabel("Concrete compressive strength")
plt.ylabel(r"Empirical probability $P(X \in I_i)$")

plt.tight_layout()
plt.show()

print("Sum of PMF:", pmf.sum())

"""##PMF, moments"""

hist, bin_edges = np.histogram(values, bins=bins)
pmf = hist / len(values)
print(pmf)

import scipy.stats as stats

mean = np.mean(values)
std = np.std(values)
skew = stats.skew(values)
kurt = stats.kurtosis(values)

print("mean:",mean)
print("std:",std)
print("skew:",skew)
print("kurt:",kurt)

"""## normal distributing fitting

Treat the normal distribution as one candidate model and evaluate how well it fits the data.

N(mean,standardeviation)
"""

from scipy.stats import norm

normal_probs = norm.cdf(bin_edges[1:], mean, std) - norm.cdf(bin_edges[:-1], mean, std)

rmse_normal = np.sqrt(np.mean((pmf - normal_probs) ** 2))

print("normal_probs:", normal_probs)
print("RMSE normal:", rmse_normal)

"""## lognormal distributing fitting

Select distributions based on the shape of the data.

The lognormal distribution only supports positive values (0 to ∞) and is right-skewed (skewness > 0)

Lognormal(shape,loc,scale)

"""

from scipy.stats import lognorm

shape, loc, scale = lognorm.fit(values, floc=0)

lognormal_probs = lognorm.cdf(bin_edges[1:], shape, loc, scale) \
                 - lognorm.cdf(bin_edges[:-1], shape, loc, scale)

rmse_lognormal = np.sqrt(np.mean((pmf - lognormal_probs) ** 2))

print("Lognormal parameters:")
print("shape =", shape)
print("loc =", loc)
print("scale =", scale)

print("\nlognormal_probs:", lognormal_probs)
print("RMSE lognormal:", rmse_lognormal)

"""## exponential distributing fitting"""

from scipy.stats import expon

loc, scale = expon.fit(values, floc=0)

exp_probs = expon.cdf(bin_edges[1:], loc=loc, scale=scale) \
           - expon.cdf(bin_edges[:-1], loc=loc, scale=scale)

rmse_exp = np.sqrt(np.mean((pmf - exp_probs) ** 2))

print("Exponential parameters:")
print("loc =", loc)
print("scale =", scale)

print("\nexp_probs:", exp_probs)
print("RMSE exponential:", rmse_exp)

"""## distribution comparison

A distribution with a lower RMSE fits the data better.


"""

print("RMSE normal:", rmse_normal)
print("RMSE lognormal:", rmse_lognormal)
print("RMSE exponential:", rmse_exp)

"""# (unlock the loc)strength distribution analysis & fitting"""

from scipy.stats import norm, lognorm, expon
import numpy as np
import scipy.stats as stats

values = df["Concrete compressive strength"].dropna()

hist, bin_edges = np.histogram(values, bins=bins)
pmf = hist / len(values)

norm_loc, norm_scale = norm.fit(values)
normal_probs = norm.cdf(bin_edges[1:], loc=norm_loc, scale=norm_scale) - norm.cdf(bin_edges[:-1], loc=norm_loc, scale=norm_scale)
rmse_normal = np.sqrt(np.mean((pmf - normal_probs) ** 2))

log_shape, log_loc, log_scale = lognorm.fit(values)
lognormal_probs = lognorm.cdf(bin_edges[1:], log_shape, loc=log_loc, scale=log_scale) - lognorm.cdf(bin_edges[:-1], log_shape, loc=log_loc, scale=log_scale)
rmse_lognormal = np.sqrt(np.mean((pmf - lognormal_probs) ** 2))

exp_loc, exp_scale = expon.fit(values)
exp_probs = expon.cdf(bin_edges[1:], loc=exp_loc, scale=exp_scale) - expon.cdf(bin_edges[:-1], loc=exp_loc, scale=exp_scale)
rmse_exp = np.sqrt(np.mean((pmf - exp_probs) ** 2))

print("Moments")
print("mean:", np.mean(values))
print("std:", np.std(values))
print("skew:", stats.skew(values))
print("kurtosis:", stats.kurtosis(values))

print("\nFitted parameters")
print("Normal: loc =", norm_loc, ", scale =", norm_scale)
print("Lognormal: shape =", log_shape, ", loc =", log_loc, ", scale =", log_scale)
print("Exponential: loc =", exp_loc, ", scale =", exp_scale)

print("\nRMSE")
print("Normal:", rmse_normal)
print("Lognormal:", rmse_lognormal)
print("Exponential:", rmse_exp)

from scipy.stats import norm, lognorm, expon

hist, bin_edges = np.histogram(values, bins=bins)
pmf = hist / len(values)
bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
bar_widths = np.diff(bin_edges)

plt.figure(figsize=(8, 5))

plt.bar(
    bin_centers,
    pmf,
    width=bar_widths,
    alpha=0.5,
    edgecolor="black",
    label="Empirical PMF"
)

plt.plot(bin_centers, normal_probs, marker="o",
         label=f"Normal (RMSE={rmse_normal:.5f})")

plt.plot(bin_centers, lognormal_probs, marker="o",
         label=f"Lognormal (RMSE={rmse_lognormal:.5f})")

plt.plot(bin_centers, exp_probs, marker="o",
         label=f"Exponential (RMSE={rmse_exp:.5f})")

plt.xlabel("Concrete compressive strength (MPa)")
plt.ylabel("Probability mass")
plt.title("Empirical PMF and Fitted Distributions")
plt.legend()
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()
plt.savefig("strength_distribution_fitting.png", dpi=300, bbox_inches="tight")
plt.show()

print("Number of bins:", bins)
print("Normal RMSE:", rmse_normal)
print("Lognormal RMSE:", rmse_lognormal)
print("Exponential RMSE:", rmse_exp)

"""# water & cement

- Select two numerical features from the dataset.
- Define the random variable (RV) functions and discrete value sets (DVS).
- Plot the marginal histograms for both features.
- Create a scatter plot of the two features.
- Compute the Pearson correlation coefficient.
- Construct a 3D joint PMF plot.
- Calculate σ₁, σ₂, and the covariance.
- Plot the corresponding bivariate Gaussian distribution.
- Interpret whether the Gaussian distribution provides a good model for the data.

## Correlation and Scatter Plot
"""

df[["Water", "Cement"]].describe()

import matplotlib.pyplot as plt
import pandas as pd

data = df[["Water", "Cement"]].dropna()

x = data["Water"]
y = data["Cement"]

import numpy as np

def freedman_diaconis_bins(series):
    series = series.dropna()
    n = len(series)

    q1 = np.percentile(series, 25)
    q3 = np.percentile(series, 75)
    iqr = q3 - q1

    bin_width = 2 * iqr * (n ** (-1/3))

    data_range = series.max() - series.min()
    bins = int(np.ceil(data_range / bin_width))

    return bin_width, bins

water_width, water_bins = freedman_diaconis_bins(df["Water"])
cement_width, cement_bins = freedman_diaconis_bins(df["Cement"])

print("Water bin width:", water_width)
print("Water bins:", water_bins)

print("Cement bin width:", cement_width)
print("Cement bins:", cement_bins)

import matplotlib.pyplot as plt

plt.figure(figsize=(13, 4))

plt.subplot(1, 3, 1)
plt.hist(x, bins=24, edgecolor="black")
plt.title("Marginal Histogram of Water")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 2)
plt.hist(y, bins=15, edgecolor="black")
plt.title("Marginal Histogram of Cement")
plt.xlabel(r"$X_1$: Cement (kg/m³)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 3)
plt.scatter(x, y, alpha=0.7)
plt.title("Scatter Plot of Water and Cement")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel(r"$X_1$: Cement (kg/m³)")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""- **Water:** Most observations are concentrated between 150 and 200 kg/m³, with a prominent peak around 190 kg/m³. The distribution appears approximately bell-shaped and resembles a weakly normal distribution.

- **Cement:** A large number of observations are concentrated around 150 kg/m³ and between 200 and 400 kg/m³. The distribution also exhibits a long right tail, suggesting a mildly right-skewed distribution.

- **Scatter plot:** No clear upward or downward linear pattern is visible. Likewise, there is no distinct line-like concentration of points. Most observations are clustered in the region Water ≈ 170–200 kg/m³ and Cement ≈ 150–350 kg/m³. Several outliers are also present. Overall, the scatter plot suggests a weak relationship and near-zero correlation between the two variables.

- **Pearson correlation:** The correlation coefficient is negative and very close to zero (|r| ≈ 0.08), indicating that the variables are nearly uncorrelated. At most, there is a very weak negative correlation (weak anticorrelation) between Water and Cement.
"""

r = x.corr(y)
print("Pearson correlation:", r)

"""## joint pmf - cement & water

- **Continuous variables:** Probability Density Function (PDF)
- **Discrete variables:** Probability Mass Function (PMF)

The term *mass* is used because probability is concentrated at specific values (or within specific intervals), rather than being spread continuously over the entire domain.

### Empirical Probability

When the sample size is sufficiently large, relative frequencies provide a good approximation of probabilities.

Empirical Probability = (Number of observations in a bin) / (Total number of observations)

Therefore, the relative frequency of observations within a bin can be interpreted as an estimate of the true probability.

### Why Examine the Joint PMF?

Unlike the Pearson correlation coefficient, the empirical joint PMF provides additional information about the structure of the data. In particular, a 3D joint PMF allows us to examine:

- where the probability mass is concentrated,
- whether the distribution exhibits regular or irregular patterns,
- whether the relationship between the variables appears weak or strong,
- and whether a Gaussian model is likely to provide a reasonable approximation of the joint distribution.
"""

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(13, 4))

plt.subplot(1, 3, 1)
water_counts, water_edges = np.histogram(x, bins=24)
water_pmf = water_counts / water_counts.sum()
water_centers = (water_edges[:-1] + water_edges[1:]) / 2
water_width = water_edges[1] - water_edges[0]

plt.bar(water_centers, water_pmf, width=water_width * 0.9, edgecolor="black")
plt.title("Empirical PMF of Water")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel(r"Empirical probability $P(X_4 \in I_i)$")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 2)
cement_counts, cement_edges = np.histogram(y, bins=15)
cement_pmf = cement_counts / cement_counts.sum()
cement_centers = (cement_edges[:-1] + cement_edges[1:]) / 2
cement_width = cement_edges[1] - cement_edges[0]

plt.bar(cement_centers, cement_pmf, width=cement_width * 0.9, edgecolor="black")
plt.title("Empirical PMF of Cement")
plt.xlabel(r"$X_1$: Cement (kg/m³)")
plt.ylabel(r"Empirical probability $P(X_1 \in J_j)$")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 3)
plt.scatter(x, y, alpha=0.7)
plt.title("Scatter Plot of Water and Cement")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel(r"$X_1$: Cement (kg/m³)")
plt.grid(alpha=0.3)


plt.tight_layout()
plt.show()

"""Water-Cement의 scatter plot이 전체적으로 퍼져있음. 즉, water을 안다고 cement를 거의 예측 못함. 이건 독립에 가까운 모습."""

import numpy as np
import matplotlib.pyplot as plt

data = df[["Water", "Cement"]].dropna()

x = data["Water"]
y = data["Cement"]

water_bins = 24
cement_bins = 15

hist2d, x_edges, y_edges = np.histogram2d(
    x,
    y,
    bins=[water_bins, cement_bins]
)

joint_pmf = hist2d / hist2d.sum()

x_centers = (x_edges[:-1] + x_edges[1:]) / 2
y_centers = (y_edges[:-1] + y_edges[1:]) / 2

Xc, Yc = np.meshgrid(x_centers, y_centers, indexing="ij")

dx = (x_edges[1] - x_edges[0]) * 0.8
dy = (y_edges[1] - y_edges[0]) * 0.8

xpos = Xc.ravel()
ypos = Yc.ravel()
zpos = np.zeros_like(xpos)

dz = joint_pmf.ravel()

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection="3d")

ax.bar3d(xpos, ypos, zpos, dx, dy, dz, shade=True)

ax.set_title("Empirical Joint PMF of Water and Cement")
ax.set_xlabel(r"$X_4$: Water (kg/m³)")
ax.set_ylabel(r"$X_1$: Cement (kg/m³)")
ax.set_zlabel(r"Joint PMF $P(X_4 \in I_i, X_1 \in J_j)$")

plt.tight_layout()
plt.show()

"""- The empirical joint distribution of Water and Cement appears irregular and sparse. A smooth and symmetric distribution would typically resemble a single hill-shaped peak centered around one dominant region.

- The higher probability masses do not align along a diagonal direction. Therefore, the joint distribution does not suggest a strong linear relationship between the two variables.

- For a bivariate Gaussian model to provide a good approximation, the joint distribution should generally exhibit a smooth elliptical or bell-shaped structure centered around a single peak. In contrast, the empirical joint PMF contains multiple local peaks and a considerable number of low-probability or empty bins, indicating departures from the assumptions of a simple Gaussian model.

## 2-variate gaussian

### Bivariate Gaussian Model

- A smooth probabilistic model constructed from the empirical mean vector, variances, and covariance.

- A bivariate Gaussian distribution typically forms a single smooth hill-shaped surface.

Its main characteristics are:

- a single central peak,
- probability density that decreases smoothly away from the center,
- an approximately circular or axis-aligned elliptical shape when the covariance is small,
- and a tilted elliptical shape when the covariance is large.

To define a bivariate Gaussian model, the following quantities are required:

- the mean vector,
- the covariance matrix.
"""

import numpy as np
import pandas as pd

data = df[["Water", "Cement"]].dropna()

x = data["Water"]
y = data["Cement"]

mu_1 = x.mean()
mu_2 = y.mean()

sigma_1 = x.std(ddof=1)
sigma_2 = y.std(ddof=1)

covariance = np.cov(x, y, ddof=1)[0, 1]

print("Mean of Water (mu_1):", mu_1)
print("Mean of Cement (mu_2):", mu_2)
print("Standard deviation of Water (sigma_1):", sigma_1)
print("Standard deviation of Cement (sigma_2):", sigma_2)
print("Covariance Cov[Water, Cement]:", covariance)

mean_vector = np.array([mu_1, mu_2])

cov_matrix = np.array([
    [sigma_1**2, covariance],
    [covariance, sigma_2**2]
])

print("Mean vector:")
print(mean_vector)

print("Covariance matrix:")
print(cov_matrix)

"""- Cement variance is much larger than Water variance.

- The Gaussian surface is expected to be more spread out in the Cement direction than in the Water direction.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

# Grid over the range of Water and Cement
x_grid = np.linspace(x.min(), x.max(), 100)
y_grid = np.linspace(y.min(), y.max(), 100)

X_grid, Y_grid = np.meshgrid(x_grid, y_grid)

# Combine grid points into coordinate pairs
pos = np.dstack((X_grid, Y_grid))

# Define 2-variate Gaussian using empirical mean and covariance
rv = multivariate_normal(mean=mean_vector, cov=cov_matrix)

# Gaussian density values
Z = rv.pdf(pos)

# 3D surface plot
fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection="3d")

ax.plot_surface(X_grid, Y_grid, Z, alpha=0.8)

ax.set_title("2-variate Gaussian Model for Water and Cement")
ax.set_xlabel(r"$X_4$: Water (kg/m³)")
ax.set_ylabel(r"$X_1$: Cement (kg/m³)")
ax.set_zlabel(r"Density $p_{X_1,X_2}(x_1,x_2)$")

plt.tight_layout()
plt.show()

"""네 empirical joint PMF는 아까 이렇게 보였어:

여러 local peak가 있음
빈 bin도 많음
불규칙하고 sparse함
하나의 매끄러운 산 모양은 아님

반면 fitted Gaussian은:

하나의 중심
smooth한 surface
symmetric/elliptical structure
평균, 분산, 공분산만 반영

그래서 결론은:

2-variate Gaussian은 rough approximation으로는 가능하지만, empirical joint PMF를 잘 설명하는 모델이라고 보기는 어렵다.
"""

plt.figure(figsize=(7, 6))

plt.contourf(X_grid, Y_grid, Z, levels=20)
plt.scatter(x, y, s=10, alpha=0.4)

plt.xlabel("Water")
plt.ylabel("Cement")
plt.title("2-variate Gaussian Contour with Data Points")
plt.colorbar(label="Gaussian density")

plt.show()

"""- The Gaussian contours are nearly vertically elongated ellipses.

- The Pearson correlation coefficient between Water and Cement is very small (r = -0.08), and neither the scatter plot nor the empirical joint PMF reveals a clear dependence structure. Therefore, the observed data do not exhibit patterns that strongly contradict an independence assumption.

- Why can we not simply conclude that the variables are independent? Independence requires that

  P(X, Y) = P(X)P(Y)

  for all possible combinations of x and y.

- If Water is discretized into 24 bins and Cement into 15 bins, this condition would need to be verified for all

  24 × 15 = 360

  cells of the joint distribution.

- In practice, the available data constitute only a finite sample, and the PMF obtained from the data is an empirical PMF rather than the true underlying PMF. Consequently, it is difficult to formally prove complete independence from the observed data alone.

- More rigorous approaches for assessing independence include the chi-square test of independence and information-theoretic measures such as mutual information.

# correlation matrix
"""

corr_matrix = df.corr(numeric_only=True)

corr_matrix

plt.figure(figsize=(10,8))

im = plt.imshow(
    corr_matrix,
    cmap="coolwarm",
    vmin=-1,
    vmax=1
)

for i in range(len(corr_matrix)):
    for j in range(len(corr_matrix)):
        plt.text(
            j,
            i,
            f"{corr_matrix.iloc[i,j]:.2f}",
            ha="center",
            va="center",
            fontsize=8
        )

plt.colorbar(im, label="Pearson Correlation")

plt.xticks(
    range(len(corr_matrix.columns)),
    corr_matrix.columns,
    rotation=45,
    ha="right"
)

plt.yticks(
    range(len(corr_matrix.columns)),
    corr_matrix.columns
)

plt.title("Correlation Matrix of Concrete Dataset")

plt.tight_layout()
plt.show()

print(df.columns.tolist())

target_corr = (
    corr_matrix["Concrete compressive strength"]
    .drop("Concrete compressive strength")
    .sort_values(ascending=False)
)

print(target_corr)

target_corr_df = pd.DataFrame({
    "Variable": target_corr.index,
    "Correlation with Concrete compressive strength": target_corr.values
})

target_corr_df

"""# strength & cement

## Correlation and Scatter Plot
"""

df[["Concrete compressive strength", "Cement"]].describe()

import matplotlib.pyplot as plt
import pandas as pd

data = df[["Concrete compressive strength", "Cement"]].dropna()

x = data["Concrete compressive strength"]
y = data["Cement"]

import numpy as np

def freedman_diaconis_bins(series):
    series = series.dropna()
    n = len(series)

    q1 = np.percentile(series, 25)
    q3 = np.percentile(series, 75)
    iqr = q3 - q1

    bin_width = 2 * iqr * (n ** (-1/3))

    data_range = series.max() - series.min()
    bins = int(np.ceil(data_range / bin_width))

    return bin_width, bins

strength_width, strength_bins = freedman_diaconis_bins(df["Concrete compressive strength"])
cement_width, cement_bins = freedman_diaconis_bins(df["Cement"])

print("Strength bin width:", strength_width)
print("Strength bins:", strength_bins)

print("Cement bin width:", cement_width)
print("Cement bins:", cement_bins)

import matplotlib.pyplot as plt

plt.figure(figsize=(13, 4))

# Strength histogram
plt.subplot(1, 3, 1)
plt.hist(x, bins=24, edgecolor="black")
plt.title("Marginal Histogram of Strength")
plt.xlabel(r"$Ｙ$: Strength (MPa)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

# Cement histogram
plt.subplot(1, 3, 2)
plt.hist(y, bins=15, edgecolor="black")
plt.title("Marginal Histogram of Cement")
plt.xlabel(r"$X_1$: Cement (kg/m³)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

# Scatter plot
plt.subplot(1, 3, 3)
plt.scatter(x, y, alpha=0.7)
plt.title("Scatter Plot of Strength and Cement")
plt.xlabel(r"$Ｙ$: Strength (MPa)")
plt.ylabel(r"$X_1$: Cement (kg/m³)")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

r = x.corr(y)
print("Pearson correlation:", r)

"""- Cement and Concrete Compressive Strength exhibit a moderate positive correlation.

- The scatter plot shows a general tendency for compressive strength to increase as cement content increases. However, the relationship is far from perfectly linear.

- For example, when the cement content is around 300 kg/m³, the observed strength values range approximately from 15 to 60 MPa. Similarly, for cement contents around 400 kg/m³, the strength values vary from about 13 to 80 MPa.

- This substantial dispersion indicates that cement alone is insufficient to explain variations in compressive strength. Instead, multiple mixture components and curing conditions jointly influence the target variable.

## joint pmf - cement & Strength
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator, FormatStrFormatter

data = df[["Concrete compressive strength", "Cement"]].dropna()

x = data["Concrete compressive strength"]
y = data["Cement"]

strength_bins = 19
cement_bins = 15

hist2d, x_edges, y_edges = np.histogram2d(
    x,
    y,
    bins=[strength_bins, cement_bins]
)

joint_pmf = hist2d / hist2d.sum()

x_centers = (x_edges[:-1] + x_edges[1:]) / 2
y_centers = (y_edges[:-1] + y_edges[1:]) / 2

Xc, Yc = np.meshgrid(x_centers, y_centers, indexing="ij")

dx = (x_edges[1] - x_edges[0]) * 0.8
dy = (y_edges[1] - y_edges[0]) * 0.8

xpos = Xc.ravel()
ypos = Yc.ravel()
zpos = np.zeros_like(xpos)

dz = joint_pmf.ravel()

fig = plt.figure(figsize=(13, 8))
ax = fig.add_subplot(111, projection="3d")

ax.bar3d(xpos, ypos, zpos, dx, dy, dz, shade=True)
ax.zaxis.set_major_locator(MaxNLocator(5))
ax.zaxis.set_major_formatter(
    FormatStrFormatter('%.3f')
)

ax.set_title("Empirical Joint PMF of Strength and Cement")
ax.set_xlabel(r"$Ｙ$: Strength (MPa)")
ax.set_ylabel(r"$X_1$: Cement (kg/m³)")
ax.set_zlabel(r"Joint PMF $P(Ｙ \in I_i, X_1 \in J_j)$")

plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))

im = plt.imshow(
    joint_pmf.T,
    origin="lower",
    aspect="auto",
    extent=[
        x_edges[0],
        x_edges[-1],
        y_edges[0],
        y_edges[-1]
    ]
)

plt.colorbar(im, label="Joint PMF")

plt.xlabel("Strength (MPa)")
plt.ylabel("Cement (kg/m³)")

plt.title(
    "Empirical Joint PMF of Concrete Strength and Cement"
)

plt.tight_layout()
plt.show()

"""- The brighter regions of the heatmap appear to extend from the lower-left toward the upper-right. This pattern suggests that larger compressive strength values tend to be associated with larger cement contents, indicating a positive relationship between the variables.

- The diagonal structure visible in the heatmap suggests that the two variables are unlikely to be independent.

- Multiple strength values are observed for the same cement content. This indicates substantial dispersion in the data and implies that the conditional distribution of strength given cement content has a relatively large spread.

- Overall, the Pearson correlation coefficient (r ≈ 0.50) indicates a moderate positive correlation between Cement and Concrete Compressive Strength. However, the scatter plot also reveals considerable dispersion. Therefore, although cement is an important predictor, it is not sufficient to explain compressive strength on its own. This suggests that multivariate modeling is required to adequately capture the variability in the target variable.

## 2-variate gaussian
"""

import numpy as np
import pandas as pd

data = df[["Concrete compressive strength", "Cement"]].dropna()

x = data["Concrete compressive strength"]
y = data["Cement"]

mu_1 = x.mean()
mu_2 = y.mean()

sigma_1 = x.std(ddof=1)
sigma_2 = y.std(ddof=1)

covariance = np.cov(x, y, ddof=1)[0, 1]

print("Mean of Strength (mu_1):", mu_1)
print("Mean of Cement (mu_2):", mu_2)
print("Standard deviation of Strength (sigma_1):", sigma_1)
print("Standard deviation of Cement (sigma_2):", sigma_2)
print("Covariance Cov[Strength, Cement]:", covariance)

mean_vector = np.array([mu_1, mu_2])

cov_matrix = np.array([
    [sigma_1**2, covariance],
    [covariance, sigma_2**2]
])

print("Mean vector:")
print(mean_vector)

print("Covariance matrix:")
print(cov_matrix)

plt.figure(figsize=(7, 6))

x_grid = np.linspace(x.min(), x.max(), 100)
y_grid = np.linspace(y.min(), y.max(), 100)

X_grid, Y_grid = np.meshgrid(x_grid, y_grid)

pos = np.dstack((X_grid, Y_grid))

rv = multivariate_normal(mean=mean_vector, cov=cov_matrix)

Z = rv.pdf(pos)

plt.contourf(X_grid, Y_grid, Z, levels=20)
plt.scatter(x, y, s=10, alpha=0.4)

plt.xlabel("Strength")
plt.ylabel("Cement")
plt.title("2-variate Gaussian Contour with Data Points")
plt.colorbar(label="Gaussian density")

plt.show()

"""- The brightest region corresponds approximately to the center of the data distribution, i.e., the area around the empirical mean values.

- The highest concentration of observations is located around:
  - Strength ≈ 35–40 MPa
  - Cement ≈ 280–320 kg/m³

- If the correlation coefficient were close to zero, the Gaussian contours would be expected to spread primarily in the vertical and horizontal directions, with little or no diagonal orientation.

- Instead, the contours form a tilted elliptical shape extending from the lower-left toward the upper-right, which is consistent with the positive correlation observed between Cement and Concrete Compressive Strength.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

x_grid = np.linspace(x.min(), x.max(), 100)
y_grid = np.linspace(y.min(), y.max(), 100)

X_grid, Y_grid = np.meshgrid(x_grid, y_grid)

pos = np.dstack((X_grid, Y_grid))

rv = multivariate_normal(mean=mean_vector, cov=cov_matrix)

Z = rv.pdf(pos)

fig = plt.figure(figsize=(13, 8))
ax = fig.add_subplot(111, projection="3d")

ax.plot_surface(X_grid, Y_grid, Z, alpha=0.8)
ax.zaxis.set_major_locator(MaxNLocator(5))
ax.zaxis.set_major_formatter(
    FormatStrFormatter('%.3f')
)

ax.set_title("2-variate Gaussian Model for Strength and Cement")
ax.set_xlabel(r"$Ｙ$: Strength (kg/m³)")
ax.set_ylabel(r"$X_1$: Cement (kg/m³)")
ax.set_zlabel(r"Density $p_{X_1,X_2}(x_1,x_2)$")

plt.tight_layout()
plt.show()

"""### What the Gaussian Model Fails to Capture

- The empirical data exhibit multiple local clusters and irregular concentration patterns, whereas a Gaussian model assumes a single smooth peak centered around one dominant location.

- Consequently, the Gaussian model captures the overall positive trend but fails to represent local structures visible in the empirical distribution.

- A bivariate Gaussian model assumes

  \[
  (X,Y) \sim N(\mu,\Sigma)
  \]

  and therefore always produces a distribution with:
  - a single center (the mean),
  - a single peak,
  - and smooth elliptical contours.

- When the empirical data contain multiple peaks or clusters, the Gaussian model effectively averages them into one large hill-shaped structure because it is determined solely by the mean vector and covariance matrix.

- If multiple peaks or clusters need to be represented explicitly, a Gaussian Mixture Model (GMM) would be more appropriate.

### Comparison with the Water–Cement Pair

- The Cement–Strength pair appears more Gaussian-like than the Water–Cement pair.

- In the Water–Cement scatter plot, the observations are broadly dispersed and resemble a diffuse cloud without a clear dominant direction.

- In contrast, the Cement–Strength scatter plot exhibits an overall upward trend.

- Since a Gaussian model always constructs a single elliptical dependence structure from the mean vector and covariance matrix, it aligns more naturally with the dominant orientation observed in the Cement–Strength data.

- Therefore, the Gaussian model provides a reasonable description of the overall dependence structure for the Cement–Strength pair, even though it does not reproduce all local features of the empirical distribution.

### Interpretation of the Gaussian Assumption

- The Gaussian assumption states that

  \[
  (X,Y) \sim N(\mu,\Sigma)
  \]

  meaning that the relationship between the variables can be characterized primarily through the mean vector, variances, and covariance.

- For the Water–Cement pair, the mean and covariance alone provide little information about the underlying relationship.

- For the Cement–Strength pair, however, the mean and covariance are sufficient to capture the main characteristic of the data, namely the overall positive association between the two variables.

# water & Superplasticizer

## Correlation and Scatter Plot
"""

df[["Water", "Superplasticizer"]].describe()

"""**ｍｏｒｅ ｔｈａｎ ２５ ‰ ｏｆ superplasticizer = 0**"""

import matplotlib.pyplot as plt
import pandas as pd

data = df[["Water", "Superplasticizer"]].dropna()

x = data["Water"]
y = data["Superplasticizer"]

import numpy as np

def freedman_diaconis_bins(series):
    series = series.dropna()
    n = len(series)

    q1 = np.percentile(series, 25)
    q3 = np.percentile(series, 75)
    iqr = q3 - q1

    bin_width = 2 * iqr * (n ** (-1/3))

    data_range = series.max() - series.min()
    bins = int(np.ceil(data_range / bin_width))

    return bin_width, bins

water_width, water_bins = freedman_diaconis_bins(df["Water"])
superplasticizer_width, superplasticizer_bins = freedman_diaconis_bins(df["Superplasticizer"])

print("water bin width:", water_width)
print("water bins:", water_bins)

print("Superplasticizer bin width:", superplasticizer_width)
print("Superplasticizer bins:", superplasticizer_bins)

import matplotlib.pyplot as plt

plt.figure(figsize=(13, 4))

plt.subplot(1, 3, 1)
plt.hist(x, bins=24, edgecolor="black")
plt.title("Marginal Histogram of Water")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 2)
plt.hist(y, bins=15, edgecolor="black")
plt.title("Marginal Histogram of Superplasticizer")
plt.xlabel(r"$X_５$: Superplasticizer (kg/m³)")
plt.ylabel("Frequency")
plt.grid(alpha=0.3)

plt.subplot(1, 3, 3)
plt.scatter(x, y, alpha=0.7)
plt.title("Scatter Plot of Water and Superplasticizer")
plt.xlabel(r"$X_4$: Water (kg/m³)")
plt.ylabel(r"$X_５$: Superplasticizer (kg/m³)")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""The marginal distribution of Superplasticizer is highly skewed, with a substantial concentration of observations at or near zero.

"""

r = x.corr(y)
print("Pearson correlation:", r)

"""The strong negative correlation suggests a substitution effect between water and superplasticizer. Mixtures containing larger amounts of superplasticizer tend to require less water while maintaining workability

## joint pmf - cement & water
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator, FormatStrFormatter

data = df[["Water", "Cement"]].dropna()

x = data["Water"]
y = data["Cement"]

water_bins = 19
cement_bins = 15

hist2d, x_edges, y_edges = np.histogram2d(
    x,
    y,
    bins=[water_bins, cement_bins]
)

joint_pmf = hist2d / hist2d.sum()

x_centers = (x_edges[:-1] + x_edges[1:]) / 2
y_centers = (y_edges[:-1] + y_edges[1:]) / 2

Xc, Yc = np.meshgrid(x_centers, y_centers, indexing="ij")

dx = (x_edges[1] - x_edges[0]) * 0.8
dy = (y_edges[1] - y_edges[0]) * 0.8

xpos = Xc.ravel()
ypos = Yc.ravel()
zpos = np.zeros_like(xpos)

dz = joint_pmf.ravel()

fig = plt.figure(figsize=(13, 8))
ax = fig.add_subplot(111, projection="3d")

ax.bar3d(xpos, ypos, zpos, dx, dy, dz, shade=True)
ax.zaxis.set_major_locator(MaxNLocator(5))
ax.zaxis.set_major_formatter(
    FormatStrFormatter('%.3f')
)

ax.set_title("Empirical Joint PMF of water and Cement")
ax.set_xlabel(r"$X_4$: Water (kg/m³)")
ax.set_ylabel(r"$X_５$: Superplasticizer (kg/m³)")
ax.set_zlabel(r"Joint PMF $P(X_4 \in I_i, X_５ \in J_j)$")

plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))

im = plt.imshow(
    joint_pmf.T,
    origin="lower",
    aspect="auto",
    extent=[
        x_edges[0],
        x_edges[-1],
        y_edges[0],
        y_edges[-1]
    ]
)

plt.colorbar(im, label="Joint PMF")

plt.xlabel("Water (kg/m³)")
plt.ylabel("Superplasticizer (kg/m³)")

plt.title(
    "Empirical Joint PMF of Water and Superplasticizer"
)

plt.tight_layout()
plt.show()

"""- Bright regions follow a downward diagonal pattern (upper-left to lower-right), consistent with the negative Pearson correlation.

- Dispersion is smaller than in the Water–Cement pair. The observations are concentrated along a negative trend rather than being randomly scattered.

- The brightest hotspot (largest local peak) is located around Water ≈ 190 kg/m³ and Superplasticizer ≈ 0 kg/m³.

## 2-variate gaussian
"""

import numpy as np
import pandas as pd

data = df[["Water", "Superplasticizer"]].dropna()

x = data["Water"]
y = data["Superplasticizer"]

mu_1 = x.mean()
mu_2 = y.mean()

sigma_1 = x.std(ddof=1)
sigma_2 = y.std(ddof=1)

covariance = np.cov(x, y, ddof=1)[0, 1]

print("Mean of Strength (mu_1):", mu_1)
print("Mean of Cement (mu_2):", mu_2)
print("Standard deviation of Strength (sigma_1):", sigma_1)
print("Standard deviation of Cement (sigma_2):", sigma_2)
print("Covariance Cov[Strength, Cement]:", covariance)

mean_vector = np.array([mu_1, mu_2])

cov_matrix = np.array([
    [sigma_1**2, covariance],
    [covariance, sigma_2**2]
])

print("Mean vector:")
print(mean_vector)

print("Covariance matrix:")
print(cov_matrix)

from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
import numpy as np

# Create grid for Water and Superplasticizer
x_grid = np.linspace(x.min(), x.max(), 100)
y_grid = np.linspace(y.min(), y.max(), 100)

X_grid, Y_grid = np.meshgrid(x_grid, y_grid)

# Combine grid points
pos = np.dstack((X_grid, Y_grid))

# Define bivariate Gaussian model
rv = multivariate_normal(
    mean=mean_vector,
    cov=cov_matrix
)

# Gaussian density on the grid
Z = rv.pdf(pos)

# Normalize density for visualization
Z = Z / Z.max()

# Plot contour with data points
plt.figure(figsize=(7, 6))

plt.contourf(X_grid, Y_grid, Z, levels=20)
plt.scatter(x, y, s=10, alpha=0.4)

plt.xlabel("Water (kg/m³)")
plt.ylabel("Superplasticizer (kg/m³)")
plt.title("2-variate Gaussian Contour with Data Points")
plt.colorbar(label="Gaussian density")

plt.tight_layout()
plt.show()

"""- The brightest region corresponds approximately to the center of the data distribution, i.e., the area around the empirical mean values.

- The highest concentration of observations is located around:
  - Water ≈ 180–190 kg/m³
  - Superplasticizer ≈ 5–7 kg/m³

- The Pearson correlation coefficient is −0.658. Consequently, the Gaussian contours are elongated along a downward-sloping direction (↘). If the correlation were close to zero, the contours would be nearly circular or aligned with the coordinate axes.

### What the Gaussian Model Fails to Capture

- The most prominent feature of the empirical heatmap is the large peak near Superplasticizer = 0. However, this feature is not reproduced by the Gaussian model.

- The reason is that the Gaussian distribution is centered around the empirical mean (μ₂ = 6.2) and spreads probability mass smoothly around that center.

- In contrast, the empirical data are heavily concentrated near zero, resulting in a strongly asymmetric distribution.

- Therefore, the Gaussian model captures the overall negative relationship between Water and Superplasticizer, but it fails to represent the pronounced concentration of observations near Superplasticizer = 0.

### Comparison with the Cement–Strength Pair

- The Water–Superplasticizer pair exhibits a stronger correlation, smaller dispersion, and a more pronounced diagonal structure than the Cement–Strength pair.

- As a result, the Gaussian model provides a better approximation of the overall dependence structure for Water–Superplasticizer than for Cement–Strength.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

x_grid = np.linspace(x.min(), x.max(), 100)
y_grid = np.linspace(y.min(), y.max(), 100)

X_grid, Y_grid = np.meshgrid(x_grid, y_grid)

pos = np.dstack((X_grid, Y_grid))

rv = multivariate_normal(mean=mean_vector, cov=cov_matrix)

Z = rv.pdf(pos)

fig = plt.figure(figsize=(13, 8))
ax = fig.add_subplot(111, projection="3d")

ax.plot_surface(X_grid, Y_grid, Z, alpha=0.8)
ax.zaxis.set_major_locator(MaxNLocator(5))
ax.zaxis.set_major_formatter(
    FormatStrFormatter('%.3f')
)

ax.set_title("2-variate Gaussian Model for Water and Superplasticizer")
ax.set_xlabel(r"$X_4$: Water (kg/m³)")
ax.set_ylabel(r"$X_５$: Superplasticizer (kg/m³)")
ax.set_zlabel(r"Density $p_{X_1,X_2}(x_1,x_2)$")

plt.tight_layout()
plt.show()